gemini_api_key: "AIzaSyAJYW7dillcNoW0cppyyvBlwuUiR5rDXpg"
weather_api_key: "279acc28e9f343db92e182213251811"
exchangerate_api_key: "f679c7fe04107e7d01baddaa"
semantic_scholar_key: "Z3RDxt793R4wsPzTRiwBVa7IcuqZrOPd1CLkqN3V"
ollama_model: "qwen2.5:7b"
